# Configuration fragment for the base of a 62-key DMOTE.

split: true
keys:
  styles:
    minimal-short:  # A printable minimal key with a thin top.
      style: minimal
      top-size: [9, 9, 1.6]
      skirt-thickness: 2.4
    minimal-tall:  # Similar but with a thicker plate above the stem.
      style: minimal
      top-size: [9, 9, 3]
      skirt-thickness: 2.4
key-clusters:
  main:
    position:
      anchor: origin
      offset: [0, 0, 27]
    matrix-columns:
    - rows-above-home: 2
      rows-below-home: 1
    - rows-above-home: 2
      rows-below-home: 1
    - rows-above-home: 2
      rows-below-home: 2
    - rows-above-home: 2
      rows-below-home: 2
    - rows-above-home: 2
      rows-below-home: 2
    - rows-above-home: 2
      rows-below-home: 1
    aliases:
      m00: [0, first]
      m01: [1, first]
      m02: [2, first]
      m03: [3, first]
      back0: [0, last]
      back1: [1, last]
      m10: [3, last]
      m11: [3, 0]
      m12: [4, last]
      near-right: [last, first]
      near-right2: [4, first]
  thumb0:
    position:
      anchor: m00
      offset: [5, -48, -3]
    matrix-columns:
    - rows-above-home: 0
    - rows-above-home: 0
    - rows-above-home: 1
    - rows-above-home: 0
    aliases:
      tc: [first, 0]
      t1: [first, last]
      t2: [last, last]
      t3: [last, first]
      t4: [first, first]
by-key:
  parameters:
    # key-style: minimal-tall
  clusters:
    main:
      parameters:
        layout:
          matrix:
            neutral:
              column: 2
            separation:
              row: -0.5
              column: 0
          pitch:
            base: 0.5
            progressive: 0.3
            intrinsic: -0.1
          roll:
            base: 0.2
            progressive: 0.06
          yaw:
            base: 0.03
      columns:
        "0":
          parameters:
            layout:
              matrix:
                separation:
                  row: -0.5
              pitch:
                base: 0.6
                progressive: 0.4
              roll:
                intrinsic: 0.3
              translation:
                mid: [-0.5, -1, 3.5]
                early: [-1.5, 0, 0]
            wall:
              north:
                extent: 0
              south:
                extent: 0
        "1":
          parameters:
            layout:
              matrix:
                separation:
                  row: -0.9
              pitch:
                base: 0.6
                progressive: 0.4
              translation:
                mid: [0, -1, 0]
            wall:
              north:
                extent: 0
              south:
                extent: 0
              west:
                extent: 0
        "2":
          parameters:
            layout:
              pitch:
                progressive: 0.4
              translation:
                mid: [0, 3, -3]
            wall:
              north:
                extent: 0
              east:
                extent: 0
              south:
                extent: 1
              west:
                extent: 0
        "3":
          parameters:
            layout:
              pitch:
                base: 0.4
                progressive: 0.45
              translation:
                mid: [0, -2, 0]
            wall:
              north:
                extent: 0
        "4":
          parameters:
            layout:
              matrix:
                separation:
                  row: -0.8
              pitch:
                base: 0.6
                progressive: 0.5
              yaw:
                base: 0.1
              translation:
                late: [0.6, -5, 5.5]
            wall:
              north:
                extent: 1
        "5":
          parameters:
            layout:
              matrix:
                separation:
                  row: -0.6
              pitch:
                base: 0.6
                progressive: 0.55
              yaw:
                base: 0.12
              translation:
                early: [1.5,0,0]
                late: [2, -6, 5.5]
              roll:
                intrinsic: -0.3
            wall:
              north:
                extent: 1
    thumb0:
      parameters:
        layout:
          matrix:
            neutral:
              column: 1
            separation:
              column: 0.1
          roll:
            base: 0
            progressive: 0.65
          pitch:
            base: -0.2
            progressive: 0.65
          yaw:
            base: 0.4
        wall:
          north:
            extent: 1
          east:
            extent: 4
          south:
            extent: 0
          west:
            extent: 0
secondaries:
  # Main-to-thumb0 cluster bridge points:
  mt00:
    anchor: m00
    corner: SSW
    segment: 0
    offset: [0, -2, 0]
  mt0:  # Main-to-thumb0 cluster bridge point 0
    anchor: m00
    corner: SSE
    segment: 0
  mt0a:
    anchor: m00
    corner: SSE
    segment: 0
    offset: [0, -2, 2]
  mt0b:
    anchor: mt0a
    offset: [4, -3, 16]
  mt0c:
    anchor: mt0b
    offset: [6, -2, 1]
  # Shims for wall posts being thinner than rear housing posts:
  rh-0:
    anchor: rear-housing
    corner: ESE
    segment: 1
    offset: [0, 0, -20]
case:
  rear-housing:
    include: true
    position:
      offsets:
        north: 15
        east: -0.2
        south: -1.8
        west: 2
    height: 72
    fasteners:
      diameter: 6
      bosses: true
      west:
        include: false
        offset: 0
      east:
        include: false
        offset: -13
  back-plate:
    beam-height: 20
    fasteners:
      diameter: 6
      distance: 30
    position:
      anchor: back1
      offset: [0, 0, 0]
  bottom-plate:
    include: true
    thickness: 0.8
    installation:
      thickness: 2.5
      fasteners:
        diameter: 4
        length: 8.5
        positions:
        - anchor: rear-housing
          corner: NNW
          offset: [3, -4]
        - anchor: rear-housing
          corner: NNE
          offset: [-2.5, -11]
        - anchor: near-right
          corner: ESE
          offset: [-4, 3]
        - anchor: near-right2
          corner: ESE
          offset: [-4, 3]
        - anchor: t4
          corner: SSW
          offset: [-1, 4]
        - anchor: t1
          corner: NNW
          offset: [3.5, -3]
  leds:
    include: true
    amount: 3
    # Settings here are for WS2818 diodes at 17 mm intervals.
    housing-size: 5.5  # Real size: 5 mm.
    emitter-diameter: 4
    interval: 16.8
mcu:
  include: true
  position:
    prefer-rear-housing: true
    anchor: back1
    corner: ENE
    offset: [0, 0, 2]
  support:
    style: lock
    stop:
      anchor: back1
      direction: east
connection:
  include: true
  socket-size: [10, 11, 17.7]  # 616E minus the vertical bar is 10 mm wide.
  position:
    prefer-rear-housing: true
    anchor: back1
    corner: ENE
    raise: true
    offset: [0, 0, -1]
wrist-rest:
  include: true
  position:
    offset: [83, -90]
  plinth-height: 2
  shape:
    spline:
      main-points:
      - position: [0, 32]
        alias: plinth-left
      - position: [20, 40]
        alias: plinth-mid0
      - position: [35, 38]
        alias: plinth-mid1
      - position: [41, 50]
      - position: [50, 63]
      - position: [68, 62]
        alias: plinth-right
      - position: [74, 42]
      - position: [63, 20]
      - position: [50, 5]
      - position: [30, 0]
      - position: [3, 2]
        alias: plinth-near
      resolution: 2
    lip:
      inset: -0.6
      height: 1.5
    pad:
      height:
        surface-range: 8
        lip-to-surface: 3
        below-lip: 2
      surface:
        edge:
          inset: 8
          resolution: 5
  rotation:
    pitch: 0.05
    roll: 0.05
  sprues:
    include: true
    inset: 10
    diameter: 12
    positions:
    - anchor: plinth-mid0
      offset: [0, -10]
    - anchor: plinth-right
      offset: [-5, -10]
  bottom-plate:
    include: true
    inset: 2
    fastener-positions:
    - anchor: plinth-mid0
      offset: [0, -3]
    - anchor: plinth-near
      offset: [3, 3]
    - anchor: plinth-right
      offset: [-2, -3]
